#!/bin/bash

# Exit build script on first failure.
set -e

# Exit on unset variable.
set -u

env_vars_to_flags() {
  set +u

  local flags=""

  if [[ -n "${SITE_TITLE}" ]]; then
    flags+=" -title \"${SITE_TITLE}\""
  fi

  if [[ -n "${SITE_SUBTITLE}" ]]; then
    flags+=" -subtitle \"${SITE_SUBTITLE}\""
  fi

  if [[ -n "${SITE_FOOTER}" ]]; then
    flags+=" -footer \"${SITE_FOOTER}\""
  fi

  if [[ "${SITE_SHOW_DOCUMENTATION}" == "false" ]]; then
    flags+=" -showdocs=false"
  fi

  if [[ -n "${PER_MINUTE_LIMIT}" ]]; then
    flags+=" -perminutelimit \"${PER_MINUTE_LIMIT}\""
  fi

  set -u

  echo "${flags}"
}

is_litestream_enabled() {
  set +ux

  local IS_ENABLED='false'

  if [[ -n "${DB_REPLICA_URL}" ]]; then
    IS_ENABLED='true';
  fi

  set -ux

  echo "${IS_ENABLED}"
}

IS_LITESTREAM_ENABLED="$(is_litestream_enabled)"
readonly IS_LITESTREAM_ENABLED

# Echo commands to stdout.
set -x

if [[ "${IS_LITESTREAM_ENABLED}" == 'true' ]]; then

  readonly DB_PATH="/app/data/store.db"
  export DB_PATH

  # Restore database from S3.
  /app/litestream restore -if-replica-exists -v "${DB_PATH}"

  # Let Litestream start LogPaste as a child process
  /app/litestream replicate \
    -exec "/app/logpaste $(env_vars_to_flags)"
    "${DB_PATH}" \
    "${DB_REPLICA_URL}"
else
  # Start server.
  eval "/app/logpaste $(env_vars_to_flags)"
fi
