#!/bin/bash

# Run this to enable all git hooks for this project.

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

# Get to app root directory
cd "$(dirname "$0")/.."

# If there's an existing symlink, remove it.
if [[ -L .git/hooks ]]
then
  rm .git/hooks
fi

# If it's a regular directory, remove all files.
if [[ -d .git/hooks ]]
then
  rm -rf .git/hooks
fi

ln -s -f ../dev-scripts/git-hooks .git/hooks
